# Generated by Django 3.0.5 on 2020-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=32)),
                ('personality', models.CharField(choices=[('LZY', 'Lazy'), ('JOK', 'Jock'), ('CKY', 'Cranky'), ('SMG', 'Smug'), ('NML', 'Normal'), ('PPY', 'Peppy'), ('STY', 'Snooty'), ('SSY', 'Sisterly')], default='Lazy', max_length=32)),
                ('species', models.CharField(choices=[('ALLIGATOR', 'Alligator'), ('ANTEATER', 'Anteater'), ('BEAR', 'Bear'), ('BIRD', 'Bird'), ('BULL', 'Bull'), ('CAT', 'Cat'), ('CHICKEN', 'Chicken'), ('COW', 'Cow'), ('CUB', 'Cub'), ('DEER', 'Deer'), ('DOG', 'Dog'), ('DUCK', 'Duck'), ('EAGLE', 'Eagle'), ('FROG', 'Frog'), ('GOAT', 'Goat'), ('GORILLA', 'Gorrilla'), ('HAMSTER', 'Hamster'), ('HIPPO', 'Hippo'), ('HORSE', 'Horse'), ('KANGAROO', 'Kangaroo'), ('KOALA', 'Koala'), ('LION', 'Lion'), ('MONKEY', 'Monkey'), ('MOUSE', 'Mouse'), ('OCTOPUS', 'Octopus'), ('OSTRICH', 'Ostrich'), ('PENGUIN', 'Penguin'), ('PIG', 'Pig'), ('RABBIT', 'Rabbit'), ('RHINO', 'Rhino'), ('SHEEP', 'Sheep'), ('SQUIRREL', 'Squirrel'), ('TIGER', 'Tiger'), ('WOLF', 'Wolf')], default='ALLIGATOR', max_length=32)),
                ('birthday', models.DateField()),
                ('catchphrase', models.CharField(max_length=32)),
            ],
        ),
    ]
