# Generated by Django 3.0.5 on 2020-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villager_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
